"use client";

import { useEffect, useRef, useState, type FormEvent } from 'react';
import { gsap } from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Checkbox } from '@/components/ui/checkbox';

const chapters=[['story','The story'],['soldier','The soldier'],['world','The world'],['comic','The comic'],['files','Classified files'],['coming-soon','Coming soon']];
const pages=[{src:'/art/original-sketch.png',name:'01 / The pencil study',note:'Original development artwork — pencil'},{src:'/art/original-color.png',name:'02 / From pencil to ink',note:'Original development artwork — color'}];
const beats=['Eyes forward.','Wrap it tight.','Find your footing.','Wait for the bell.','Pull back.','Turn into it.','Make it count.','And then… silence.'];
const files=[
 {type:'PERSONNEL FILE',id:'U07 / 001',status:'CLASSIFIED',title:'The soldier',body:'SUBJECT: ███████\nUNIT: 07\nRANK: █████\nSTATUS: ACTIVE\n\nCombat assessment: exceptional.\nPsychological assessment: withheld.\n\nSubject continues to report for duty. Further evaluation has been denied by command.'},
 {type:'INCIDENT REPORT',id:'U07 / 074',status:'REDACTED',title:'Seventy-four hours',body:'LOCATION: Training facility\nTIME: 03:17\nWITNESSES: █████████\n\nThe official account contains no record of the missing hours.\n\nSecurity footage: unavailable.\nMedical report: sealed.\n\n“Do not submit a second request.”'},
 {type:'COMMAND ORDER',id:'U07 / 009',status:'EYES ONLY',title:'Follow the order',body:'TO: All active personnel\nFROM: █████████\n\nAll movement beyond the perimeter requires written authorization.\n\nDo not discuss reassignment.\nDo not enter the lower level.\nDo not ask about the names removed from the roster.\n\nBY ORDER OF COMMAND.'},
 {type:'CASUALTY REPORT',id:'U07 / 026',status:'MISSING',title:'An empty locker',body:'SUBJECT: ███████\nLAST SEEN: Barracks, east wing\nSTATUS: MISSING\n\nPersonal effects remain in the locker.\nNo transfer has been recorded.\n\nThe family has not been notified.\n\nFILE CLOSED.'}
];

export default function Comic(){
 const root=useRef<HTMLElement>(null);
 const fightRef=useRef<HTMLElement>(null);
 const cursor=useRef<HTMLDivElement>(null);
 const [menu,setMenu]=useState(false);
 const [reader,setReader]=useState<number|null>(null);
 const [zoom,setZoom]=useState(1);
 const [file,setFile]=useState<number|null>(null);
 const [page,setPage]=useState(1);
 const [beat,setBeat]=useState(0);
 const [sketch,setSketch]=useState(true);
 const [motion,setMotion]=useState(true);
 const [consent,setConsent]=useState(false);
 const [status,setStatus]=useState<'idle'|'sending'|'success'|'error'>('idle');
 const [feedback,setFeedback]=useState('');

 useEffect(()=>{setMotion(!window.matchMedia('(prefers-reduced-motion: reduce)').matches)},[]);
 useEffect(()=>{
  gsap.registerPlugin(ScrollTrigger);
  const ctx=gsap.context(()=>{
   if(motion){
    gsap.from('.hero-art',{opacity:0,scale:1.04,duration:1.4,ease:'power2.out'});
    gsap.from('.hero-copy > *',{y:18,opacity:0,stagger:.09,duration:.65,delay:.2});
    gsap.utils.toArray<HTMLElement>('.reveal').forEach((el,i)=>gsap.from(el,{y:45,opacity:0,rotation:i%2?1:-1,duration:.8,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 91%',once:true}}));
    gsap.to('.hero-art',{yPercent:8,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
    gsap.to('.world-art',{yPercent:9,ease:'none',scrollTrigger:{trigger:'#world',start:'top bottom',end:'bottom top',scrub:1}});
    ScrollTrigger.create({trigger:fightRef.current,start:'top top',end:'bottom bottom',onUpdate:self=>setBeat(Math.min(7,Math.floor(self.progress*8)))});
   }
  },root);
  const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting)setPage(Number((entry.target as HTMLElement).dataset.page))},{rootMargin:'-25% 0px -40% 0px'});
  document.querySelectorAll('[data-page]').forEach(el=>observer.observe(el));
  return()=>{ctx.revert();observer.disconnect()};
 },[motion]);
 useEffect(()=>{if(reader===null)return;const key=(e:KeyboardEvent)=>{if(e.key==='ArrowRight'){setReader(p=>Math.min(p!+1,pages.length-1));setZoom(1)}if(e.key==='ArrowLeft'){setReader(p=>Math.max(p!-1,0));setZoom(1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[reader]);
 useEffect(()=>{if(!motion || !matchMedia('(pointer:fine)').matches)return;const move=(e:PointerEvent)=>{if(!cursor.current)return;cursor.current.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;const target=(e.target as HTMLElement).closest('[data-cursor],a,button');cursor.current.dataset.active=target?'true':'false';cursor.current.dataset.label=target?.getAttribute('data-cursor')||''};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move)},[motion]);
 async function join(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setStatus('sending');setFeedback('');const data=new FormData(form);try{const response=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.get('email'),website:data.get('website'),consent})});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'Please try again in a moment.');setStatus('success');setFeedback('You’re on the list. We’ll email you when Issue 001 is ready.');form.reset();setConsent(false)}catch(err){setStatus('error');setFeedback(err instanceof Error?err.message:'Could not save your email. Please try again.')}}
 function openReader(index:number){setReader(index);setZoom(1)}

 return <main ref={root} data-motion={motion}>
  <a className="skip-link" href="#story">Skip to the story</a>
  <header className="masthead"><a className="wordmark" href="#home" aria-label="Unit 07 home">UNIT 07<span aria-hidden="true">▥</span></a><span className="edition">AN ORIGINAL GRAPHIC NOVEL</span><button className="menu-button" onClick={()=>setMenu(true)} aria-haspopup="dialog">MENU <b>＋</b></button></header>
  <section className="hero" id="home" data-page="1"><img className="hero-art" src="/art/locker-room.webp" alt="A bruised soldier sits with wrapped fists in a dark military locker room" fetchPriority="high"/><div className="hero-shade"/><div className="dust" aria-hidden="true"/><div className="hero-copy"><p className="eyebrow">ISSUE 001 <span/> COMING SOON</p><h1>EVERY SOLDIER<br/>HAS A<br/><em>BREAKING POINT.</em></h1><p className="hero-intro">They taught him how to fight.<br/>Never what he was fighting for.</p><a className="red-button" href="#story" data-cursor="ENTER">ENTER THE STORY <span>↘</span></a><a className="text-link" href="#comic">Explore the comic ↗</a></div><p className="hero-caption">THE WAR DOESN’T END<br/>WHEN YOU COME HOME.</p><div className="hero-bottom"><a href="#story">↓ &nbsp; SCROLL TO TURN THE PAGE</a><span>01 — THE QUIET BEFORE</span></div></section>
  <div className="issue-strip"><span>WAR LEAVES A MARK.</span><span>SO DOES THE TRUTH.</span><span>ISSUE 001 / IN DEVELOPMENT</span></div>
  <section id="story" data-page="2" className="story-opening"><div className="story-heading reveal"><div><p className="eyebrow">PAGE 002 / THE STORY</p><h2>SOME FIGHTS<br/>FOLLOW YOU HOME.</h2></div><p>In the ring, you know your enemy.<br/><br/>Outside it, the uniform makes that harder.<br/><br/>A story about the orders we follow.<br/>And the ones that break us.</p></div><div className="story-panels"><div className="comic-panel detail-eyes reveal"><img src="/art/locker-room.webp" alt="The soldier’s lowered eyes" loading="lazy"/><span className="panel-caption">FIRST, YOU LEARN TO TAKE A HIT.</span><span className="panel-no">01</span></div><div className="comic-panel detail-wrap reveal"><img src="/art/locker-room.webp" alt="White boxing wraps around his hands" loading="lazy"/><span className="panel-caption bottom-caption">THEN, YOU LEARN TO HIDE IT.</span><span className="panel-no">02</span></div><div className="comic-panel black-panel reveal"><span className="tiny-label">03:17 A.M. / BARRACKS</span><p>“You still think<br/>we’re fighting<br/>for them?”</p><span className="dialogue-reply">“We’re fighting because<br/>they told us to.”</span></div></div><div className="story-last reveal">THAT’S NOT THE SAME THING.</div></section>
  <section id="fight" className={`fight ${motion?'':'still-fight'}`} ref={fightRef} data-page="3"><div className="fight-sticky"><div className="fight-top"><p className="eyebrow">PAGE 003 / BETWEEN THE ROPES</p><span>ROUND 01</span></div><img className="fight-art" src="/art/boxing-punch.webp" alt="The soldier throws a red-gloved punch toward his opponent" loading="lazy"/><div className="fight-vignette"/><div className="fight-title"><span className="eyebrow">EIGHT MOMENTS. ONE WAY OUT.</span><h2>NO ORDERS.<br/>JUST INSTINCT.</h2></div><div className={`fight-frame beat-${beat}`} aria-label={`Comic frame ${beat+1}: ${beats[beat]}`} style={{backgroundPosition:`${(beat%4)*100/3}% ${beat<4?0:100}%`}}/><span className={`impact ${beat===6?'impact-visible':''}`} aria-hidden="true">THUD!</span><div className="fight-caption"><span>0{beat+1} / 08</span><p>{beats[beat]}</p></div><div className="fight-timeline">{beats.map((label,i)=><button key={label} className={beat===i?'active':''} aria-label={`View frame ${i+1}: ${label}`} aria-pressed={beat===i} onClick={()=>{setBeat(i);if(motion&&fightRef.current){const el=fightRef.current;window.scrollTo({top:el.offsetTop+(el.offsetHeight-window.innerHeight)*(i+.15)/8,behavior:'instant'})}}}><span>0{i+1}</span></button>)}</div><p className="fight-instruction">{motion?'KEEP SCROLLING TO FOLLOW THE FIGHT':'SELECT A FRAME TO FOLLOW THE FIGHT'} ↓</p></div></section>
  <section id="soldier" className="soldier" data-page="4"><div className="soldier-art reveal"><img src="/art/locker-room.webp" alt="The soldier, alone on the locker-room bench" loading="lazy"/><span className="stamp">CLASSIFIED</span><div className="soldier-number" aria-hidden="true">07</div></div><div className="soldier-copy reveal"><p className="eyebrow">PAGE 004 / PERSONNEL FILE</p><h2>A NUMBER.<br/>A UNIFORM.<br/><em>A HUMAN BEING.</em></h2><dl><div><dt>SUBJECT</dt><dd><span className="redacted">NAME WITHHELD</span></dd></div><div><dt>UNIT</dt><dd>07</dd></div><div><dt>STATUS</dt><dd>ACTIVE</dd></div><div><dt>RANK</dt><dd><span className="redacted">WITHHELD</span></dd></div></dl><p>His hands remember every fight.<br/>His head won’t let him forget the rest.</p><button className="text-link" onClick={()=>setFile(0)} data-cursor="ACCESS">OPEN PERSONNEL FILE ↗</button></div></section>
  <section id="world" className="world" data-page="5"><img className="world-art" src="/art/military-compound.webp" alt="Soldiers approach a looming military command building through smoke" loading="lazy"/><div className="world-shade"/><div className="world-copy reveal"><p className="eyebrow">PAGE 005 / THE MACHINE</p><h2>THEY CALL<br/>IT DUTY.</h2><p>Every order comes from somewhere.<br/>Every silence protects someone.</p></div><p className="world-caption">DOWN HERE, WE’RE ALL EXPENDABLE.</p></section>
  <section className="command"><div className="command-heading reveal"><p className="eyebrow">BEHIND CLOSED DOORS</p><h2>THE BOARD IS SET.<br/><span>YOU’RE THE PIECE.</span></h2></div><div className="command-page reveal"><img src="/art/command-page.webp" alt="Comic panels show a commander, soldier chess pieces, a military convoy, surveillance, and a locked room" loading="lazy"/><span className="panel-caption">SOME WARS ARE WON WITHOUT FIRING A SHOT.</span><span className="command-label">ACCESS TO LOWER LEVEL: DENIED</span></div><div className="silence reveal"><span>████████████</span><p>There was a name on that locker yesterday.</p><span>████████</span></div></section>
  <section id="files" className="files" data-page="6"><div className="section-top reveal"><div><p className="eyebrow">PAGE 006 / RESTRICTED ARCHIVE</p><h2>READ BETWEEN<br/>THE REDACTIONS.</h2></div><p>Four files.<br/>One story they don’t want told.<br/><span>SELECT A FILE TO OPEN ↘</span></p></div><div className="file-stack">{files.map((f,i)=><button className={`file-sheet file-${i} reveal`} key={f.id} onClick={()=>setFile(i)} data-cursor="ACCESS"><span className="file-code">{f.id} <span>↗</span></span><span className="file-type">{f.type}</span><span className="fake-redactions" aria-hidden="true"><i/><i/><i/></span><span className="file-stamp">{f.status}</span><span className="file-bottom">DEPARTMENT OF DEFENSE / UNIT 07</span></button>)}</div><p className="archive-note">FICTIONAL ARCHIVE · A GLIMPSE INSIDE THE WORLD OF UNIT 07</p></section>
  <section id="comic" className="comic" data-page="7"><div className="section-top reveal"><div><p className="eyebrow">PAGE 007 / FROM THE DRAWING BOARD</p><h2>BEFORE THE WAR.<br/><span>THERE WAS A LINE.</span></h2></div><p>Every panel starts with a pencil.<br/>A first look at the pages in progress.</p></div><div className="comic-workbench"><div className="sketch-controls"><span>THE MAKING OF A PANEL</span><div role="group" aria-label="Artwork stage"><button aria-pressed={sketch} className={sketch?'selected':''} onClick={()=>setSketch(true)}>01 / PENCIL</button><button aria-pressed={!sketch} className={!sketch?'selected':''} onClick={()=>setSketch(false)}>02 / COLOR</button></div></div><button className="main-page" onClick={()=>openReader(sketch?0:1)} data-cursor="VIEW" aria-label={`Open ${sketch?'pencil':'color'} comic page fullscreen`}><img key={sketch?"sketch":"color"} src={pages[sketch?0:1].src} alt={sketch?'Original pencil comic page showing the boxer in a locker room':'Original colored comic page showing the boxer and wrapped hands'} loading="lazy"/><span className="view-page">EXPLORE PAGE ＋</span></button><div className="page-notes"><span className="hand-note">From the<br/>artist’s desk. ↙</span><p>Rough lines.<br/>Real weight.<br/>Nothing clean<br/>about this story.</p><span className="small-note">ORIGINAL DEVELOPMENT PAGES<br/>ARTWORK IN PROGRESS</span><button className="red-button" onClick={()=>openReader(0)}>OPEN THE READER <span>↗</span></button></div></div></section>
  <section id="coming-soon" className="coming" data-page="8"><div className="cover reveal"><img src="/art/boxing-punch.webp" alt="Unit 07 concept cover featuring the soldier boxer" loading="lazy"/><div className="cover-top"><span>AN ORIGINAL GRAPHIC NOVEL</span><span>ISSUE<br/><b>001</b></span></div><div className="cover-title">UNIT <span>07</span></div><p>A NEW STORY BEGINS.</p><span className="cover-edition">CONCEPT COVER / IN DEVELOPMENT</span></div><div className="coming-copy reveal"><p className="eyebrow">THE FIRST ISSUE IS ON ITS WAY.</p><h2>COMING<br/><em>SOON.</em></h2><p className="tagline">THE WAR WAS NEVER<br/>WHAT THEY TOLD YOU.</p><form onSubmit={join}><label htmlFor="email">BE THE FIRST TO READ ISSUE 001.</label><div className="email-row"><input type="email" name="email" id="email" autoComplete="email" placeholder="YOUR EMAIL ADDRESS" maxLength={254} required disabled={status==='sending'}/><button type="submit" disabled={status==='sending'||!consent}>{status==='sending'?'SAVING…':'GET NOTIFIED ↗'}</button></div><div className="honeypot" aria-hidden="true"><label>Leave this empty<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="I agree to receive launch updates"/><span>Email me about the launch of Unit 07. My address will only be used for these updates.</span></label><p role="status" className={`form-status ${status}`}>{feedback}</p></form></div></section>
  <footer><a className="wordmark" href="#home">UNIT 07<span aria-hidden="true">▥</span></a><p>AN ORIGINAL STORY. A DIFFERENT KIND OF WAR.</p><a href="#home">BACK TO THE FIRST PAGE ↑</a></footer>
  <div className="reading-status"><span>ISSUE 001 / PAGE {String(page).padStart(2,'0')}</span><button onClick={()=>setMotion(v=>!v)} aria-pressed={!motion}>{motion?'Ⅱ REDUCE MOTION':'▶ ENABLE MOTION'}</button></div>
  {motion&&<div className="comic-cursor" ref={cursor} aria-hidden="true"/>}
  <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="comic-menu" aria-describedby="menu-desc"><DialogTitle className="menu-title">CHOOSE YOUR CHAPTER.</DialogTitle><DialogDescription id="menu-desc">UNIT 07 / ISSUE 001</DialogDescription><nav>{chapters.map(([id,label],i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}><span>0{i+1}</span>{label}<b>↗</b></a>)}</nav></DialogContent></Dialog>
  <Dialog open={reader!==null} onOpenChange={v=>{if(!v)setReader(null)}}><DialogContent className="reader-dialog"><DialogTitle>{reader!==null?pages[reader].name:'Comic reader'}</DialogTitle><DialogDescription>Development artwork. Use the controls or arrow keys to turn the page. Escape closes the reader.</DialogDescription><div className="reader-scroll">{reader!==null&&<img src={pages[reader].src} alt={pages[reader].note} style={{width:`${zoom*100}%`,maxWidth:'none'}}/>}</div><div className="reader-controls"><button onClick={()=>{setReader(p=>Math.max(0,p!-1));setZoom(1)}} disabled={reader===0}>← PREVIOUS</button><button onClick={()=>setZoom(z=>z===1?1.6:1)}>{zoom===1?'ZOOM ＋':'FIT PAGE −'}</button><span>{(reader??0)+1} / {pages.length}</span><button onClick={()=>{setReader(p=>Math.min(pages.length-1,p!+1));setZoom(1)}} disabled={reader===pages.length-1}>NEXT →</button></div></DialogContent></Dialog>
  <Dialog open={file!==null} onOpenChange={v=>{if(!v)setFile(null)}}><DialogContent className="dossier-dialog"><DialogTitle>{file!==null?files[file].type:'Classified file'}</DialogTitle><DialogDescription>FICTIONAL STORY ARCHIVE / {file!==null?files[file].id:''}</DialogDescription><span className="dossier-stamp">{file!==null?files[file].status:''}</span><pre>{file!==null?files[file].body:''}</pre><p className="dossier-foot">UNAUTHORIZED DUPLICATION PROHIBITED</p></DialogContent></Dialog>
 </main>
}



